//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int IdUsuario { get; set; }
        public int CedulaUsuario { get; set; }
        public string Nombre { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public int IdCategoria { get; set; }
        public int Telefono1 { get; set; }
        public Nullable<int> Telefono2 { get; set; }
        public Nullable<bool> ServicioAdomicilio { get; set; }
        public Nullable<double> Calificacion { get; set; }
        public int Edad { get; set; }
        public string Email { get; set; }
        public Nullable<int> IdCita { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdProvincia { get; set; }
        public Nullable<int> IdCanton { get; set; }
        public string Detalle { get; set; }
        public Nullable<int> IdDistrito { get; set; }
        public string Longitud { get; set; }
        public string Latitud { get; set; }
    
        public virtual Canton Canton { get; set; }
        public virtual Categoria Categoria { get; set; }
        public virtual Cita Cita { get; set; }
        public virtual Distrito Distrito { get; set; }
        public virtual Provincia Provincia { get; set; }
    }
}
